<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5exV0DO\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5exV0DO/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container5exV0DO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container5exV0DO\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container5exV0DO\srcApp_KernelProdContainer([
    'container.build_hash' => '5exV0DO',
    'container.build_id' => '76ef3b6f',
    'container.build_time' => 1556277814,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5exV0DO');
