<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVVd6IMc\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVVd6IMc/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVVd6IMc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVVd6IMc\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerVVd6IMc\srcApp_KernelProdContainer([
    'container.build_hash' => 'VVd6IMc',
    'container.build_id' => 'f0b2bf42',
    'container.build_time' => 1556208095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVVd6IMc');
