<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG37TDox\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG37TDox/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerG37TDox.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerG37TDox\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerG37TDox\srcApp_KernelProdContainer([
    'container.build_hash' => 'G37TDox',
    'container.build_id' => '4d3a667d',
    'container.build_time' => 1556210535,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG37TDox');
