<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5iM2kDV' shared service.

return $this->privates['.service_locator.5iM2kDV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'user' => ['privates', '.errored..service_locator.5iM2kDV.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.5iM2kDV": it references class "App\\Entity\\User" but no such service exists.'],
]);
