<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.form_debug' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Command/DebugCommand.php';

$this->privates['console.command.form_debug'] = $instance = new \Symfony\Component\Form\Command\DebugCommand(($this->privates['form.registry'] ?? $this->load('getForm_RegistryService.php')), [0 => 'Symfony\\Component\\Form\\Extension\\Core\\Type', 1 => 'App\\Form', 2 => 'Symfony\\Bridge\\Doctrine\\Form\\Type'], [0 => 'App\\Form\\CharpenteType', 1 => 'App\\Form\\ClimatisationType', 2 => 'App\\Form\\CloisonsType', 3 => 'App\\Form\\DomotiqueType', 4 => 'App\\Form\\ElevationType', 5 => 'App\\Form\\EtudeSolType', 6 => 'App\\Form\\ExcavationType', 7 => 'App\\Form\\FondationType', 8 => 'App\\Form\\MenuiserieType', 9 => 'App\\Form\\PlancherType', 10 => 'App\\Form\\PreparationEtAccesType', 11 => 'App\\Form\\ProjetType', 12 => 'App\\Form\\SoubassementType', 13 => 'App\\Form\\ToitureType', 14 => 'App\\Form\\UserType', 15 => 'App\\Form\\VentilationType', 16 => 'App\\Form\\VrdType', 17 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType', 18 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType', 19 => 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType'], [0 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\TransformationFailureExtension', 1 => 'Symfony\\Component\\Form\\Extension\\HttpFoundation\\Type\\FormTypeHttpFoundationExtension', 2 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\FormTypeValidatorExtension', 3 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\RepeatedTypeValidatorExtension', 4 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\SubmitTypeValidatorExtension', 5 => 'Symfony\\Component\\Form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension', 6 => 'Symfony\\Component\\Form\\Extension\\DataCollector\\Type\\DataCollectorTypeExtension'], [0 => 'Symfony\\Component\\Form\\Extension\\Validator\\ValidatorTypeGuesser', 1 => 'Symfony\\Bridge\\Doctrine\\Form\\DoctrineOrmTypeGuesser']);

$instance->setName('debug:form');

return $instance;
