<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.d24Amjx' shared service.

return $this->privates['.service_locator.d24Amjx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authUtils' => ['services', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService.php', true],
]);
