<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMNnVKB5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMNnVKB5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMNnVKB5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMNnVKB5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMNnVKB5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MNnVKB5',
    'container.build_id' => '93c1b8f8',
    'container.build_time' => 1553110954,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMNnVKB5');
