<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCDDqH70\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCDDqH70/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCDDqH70.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCDDqH70\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCDDqH70\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CDDqH70',
    'container.build_id' => '00da6e9a',
    'container.build_time' => 1553190680,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCDDqH70');
