<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vrd extends \App\Entity\Vrd implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'distanceEauPotable', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'pompeRelevage', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'fosseSeptique', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'microStation', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'etudeHydrogeologique', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'distanceElectricite', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'distanceTelephonique'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'distanceEauPotable', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'pompeRelevage', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'fosseSeptique', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'microStation', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'etudeHydrogeologique', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'distanceElectricite', '' . "\0" . 'App\\Entity\\Vrd' . "\0" . 'distanceTelephonique'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vrd $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDistanceEauPotable(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistanceEauPotable', []);

        return parent::getDistanceEauPotable();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistanceEauPotable(?float $distanceEauPotable): \App\Entity\Vrd
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistanceEauPotable', [$distanceEauPotable]);

        return parent::setDistanceEauPotable($distanceEauPotable);
    }

    /**
     * {@inheritDoc}
     */
    public function getPompeRelevage(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPompeRelevage', []);

        return parent::getPompeRelevage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPompeRelevage(?bool $pompeRelevage): \App\Entity\Vrd
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPompeRelevage', [$pompeRelevage]);

        return parent::setPompeRelevage($pompeRelevage);
    }

    /**
     * {@inheritDoc}
     */
    public function getFosseSeptique(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFosseSeptique', []);

        return parent::getFosseSeptique();
    }

    /**
     * {@inheritDoc}
     */
    public function setFosseSeptique(bool $fosseSeptique): \App\Entity\Vrd
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFosseSeptique', [$fosseSeptique]);

        return parent::setFosseSeptique($fosseSeptique);
    }

    /**
     * {@inheritDoc}
     */
    public function getMicroStation(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMicroStation', []);

        return parent::getMicroStation();
    }

    /**
     * {@inheritDoc}
     */
    public function setMicroStation(bool $microStation): \App\Entity\Vrd
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMicroStation', [$microStation]);

        return parent::setMicroStation($microStation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudeHydrogeologique(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudeHydrogeologique', []);

        return parent::getEtudeHydrogeologique();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtudeHydrogeologique(bool $etudeHydrogeologique): \App\Entity\Vrd
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtudeHydrogeologique', [$etudeHydrogeologique]);

        return parent::setEtudeHydrogeologique($etudeHydrogeologique);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistanceElectricite(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistanceElectricite', []);

        return parent::getDistanceElectricite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistanceElectricite(float $distanceElectricite): \App\Entity\Vrd
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistanceElectricite', [$distanceElectricite]);

        return parent::setDistanceElectricite($distanceElectricite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistanceTelephonique(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistanceTelephonique', []);

        return parent::getDistanceTelephonique();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistanceTelephonique(float $distanceTelephonique): \App\Entity\Vrd
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistanceTelephonique', [$distanceTelephonique]);

        return parent::setDistanceTelephonique($distanceTelephonique);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\Vrd
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

}
