<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SecondOeuvre extends \App\Entity\SecondOeuvre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idEnduitFacade', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idIsolation', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idRevetement', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idCloisons', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idEvacuation', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idMenuiseriesInt', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idEscaliers', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idPlomberie', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idElectricite', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idVentilation', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idClimatisation', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idDomotique'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idEnduitFacade', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idIsolation', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idRevetement', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idCloisons', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idEvacuation', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idMenuiseriesInt', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idEscaliers', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idPlomberie', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idElectricite', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idVentilation', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idClimatisation', '' . "\0" . 'App\\Entity\\SecondOeuvre' . "\0" . 'idDomotique'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SecondOeuvre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEnduitFacade(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEnduitFacade', []);

        return parent::getIdEnduitFacade();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEnduitFacade(?int $idEnduitFacade): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEnduitFacade', [$idEnduitFacade]);

        return parent::setIdEnduitFacade($idEnduitFacade);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdIsolation(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdIsolation', []);

        return parent::getIdIsolation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdIsolation(?int $idIsolation): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdIsolation', [$idIsolation]);

        return parent::setIdIsolation($idIsolation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRevetement(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRevetement', []);

        return parent::getIdRevetement();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRevetement(?int $idRevetement): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRevetement', [$idRevetement]);

        return parent::setIdRevetement($idRevetement);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCloisons(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCloisons', []);

        return parent::getIdCloisons();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCloisons(?int $idCloisons): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCloisons', [$idCloisons]);

        return parent::setIdCloisons($idCloisons);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEvacuation(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEvacuation', []);

        return parent::getIdEvacuation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEvacuation(?int $idEvacuation): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEvacuation', [$idEvacuation]);

        return parent::setIdEvacuation($idEvacuation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMenuiseriesInt(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMenuiseriesInt', []);

        return parent::getIdMenuiseriesInt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMenuiseriesInt(?int $idMenuiseriesInt): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMenuiseriesInt', [$idMenuiseriesInt]);

        return parent::setIdMenuiseriesInt($idMenuiseriesInt);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEscaliers(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEscaliers', []);

        return parent::getIdEscaliers();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEscaliers(?int $idEscaliers): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEscaliers', [$idEscaliers]);

        return parent::setIdEscaliers($idEscaliers);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPlomberie(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPlomberie', []);

        return parent::getIdPlomberie();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPlomberie(?int $idPlomberie): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPlomberie', [$idPlomberie]);

        return parent::setIdPlomberie($idPlomberie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdElectricite(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdElectricite', []);

        return parent::getIdElectricite();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdElectricite(?int $idElectricite): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdElectricite', [$idElectricite]);

        return parent::setIdElectricite($idElectricite);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVentilation(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVentilation', []);

        return parent::getIdVentilation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdVentilation(?int $idVentilation): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVentilation', [$idVentilation]);

        return parent::setIdVentilation($idVentilation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdClimatisation(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdClimatisation', []);

        return parent::getIdClimatisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdClimatisation(?int $idClimatisation): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdClimatisation', [$idClimatisation]);

        return parent::setIdClimatisation($idClimatisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDomotique(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDomotique', []);

        return parent::getIdDomotique();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDomotique(?int $idDomotique): \App\Entity\SecondOeuvre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDomotique', [$idDomotique]);

        return parent::setIdDomotique($idDomotique);
    }

}
