<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PreparationEtAcces extends \App\Entity\PreparationEtAcces implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_pins', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_sapins', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_bouleaux', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_chenes', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_erables', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_frenes', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_noyers', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_autres', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_pins', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_sapins', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_bouleaux', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_chenes', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_erables', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_frenes', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_noyers', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_autres', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'positionTerrain', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'prix'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_pins', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_sapins', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_bouleaux', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_chenes', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_erables', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_frenes', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_noyers', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'nb_autres', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_pins', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_sapins', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_bouleaux', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_chenes', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_erables', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_frenes', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_noyers', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'taille_autres', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'positionTerrain', '' . "\0" . 'App\\Entity\\PreparationEtAcces' . "\0" . 'prix'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PreparationEtAcces $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPins(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPins', []);

        return parent::getNbPins();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPins(int $nb_pins): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPins', [$nb_pins]);

        return parent::setNbPins($nb_pins);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbSapins(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbSapins', []);

        return parent::getNbSapins();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbSapins(int $nb_sapins): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbSapins', [$nb_sapins]);

        return parent::setNbSapins($nb_sapins);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbBouleaux(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbBouleaux', []);

        return parent::getNbBouleaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbBouleaux(int $nb_bouleaux): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbBouleaux', [$nb_bouleaux]);

        return parent::setNbBouleaux($nb_bouleaux);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbChenes(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbChenes', []);

        return parent::getNbChenes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbChenes(int $nb_chenes): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbChenes', [$nb_chenes]);

        return parent::setNbChenes($nb_chenes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbErables(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbErables', []);

        return parent::getNbErables();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbErables(int $nb_erables): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbErables', [$nb_erables]);

        return parent::setNbErables($nb_erables);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbFrenes(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbFrenes', []);

        return parent::getNbFrenes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbFrenes(int $nb_frenes): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbFrenes', [$nb_frenes]);

        return parent::setNbFrenes($nb_frenes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbNoyers(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbNoyers', []);

        return parent::getNbNoyers();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbNoyers(int $nb_noyers): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbNoyers', [$nb_noyers]);

        return parent::setNbNoyers($nb_noyers);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbAutres(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbAutres', []);

        return parent::getNbAutres();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbAutres(int $nb_autres): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbAutres', [$nb_autres]);

        return parent::setNbAutres($nb_autres);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaillePins(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaillePins', []);

        return parent::getTaillePins();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaillePins(float $taille_pins): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaillePins', [$taille_pins]);

        return parent::setTaillePins($taille_pins);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailleSapins(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailleSapins', []);

        return parent::getTailleSapins();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailleSapins(float $taille_sapins): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailleSapins', [$taille_sapins]);

        return parent::setTailleSapins($taille_sapins);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailleBouleaux(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailleBouleaux', []);

        return parent::getTailleBouleaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailleBouleaux(float $taille_bouleaux): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailleBouleaux', [$taille_bouleaux]);

        return parent::setTailleBouleaux($taille_bouleaux);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailleChenes(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailleChenes', []);

        return parent::getTailleChenes();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailleChenes(float $taille_chenes): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailleChenes', [$taille_chenes]);

        return parent::setTailleChenes($taille_chenes);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailleErables(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailleErables', []);

        return parent::getTailleErables();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailleErables(float $taille_erables): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailleErables', [$taille_erables]);

        return parent::setTailleErables($taille_erables);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailleFrenes(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailleFrenes', []);

        return parent::getTailleFrenes();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailleFrenes(float $taille_frenes): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailleFrenes', [$taille_frenes]);

        return parent::setTailleFrenes($taille_frenes);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailleNoyers(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailleNoyers', []);

        return parent::getTailleNoyers();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailleNoyers(float $taille_noyers): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailleNoyers', [$taille_noyers]);

        return parent::setTailleNoyers($taille_noyers);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailleAutres(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailleAutres', []);

        return parent::getTailleAutres();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailleAutres(float $taille_autres): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailleAutres', [$taille_autres]);

        return parent::setTailleAutres($taille_autres);
    }

    /**
     * {@inheritDoc}
     */
    public function getPositionTerrain(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPositionTerrain', []);

        return parent::getPositionTerrain();
    }

    /**
     * {@inheritDoc}
     */
    public function setPositionTerrain(string $positionTerrain): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPositionTerrain', [$positionTerrain]);

        return parent::setPositionTerrain($positionTerrain);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\PreparationEtAcces
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

}
