<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Electricite extends \App\Entity\Electricite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbChauffage', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbInterrupteur', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbSortieLumieres', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbPriseElectrique', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbVoletRoulant', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'dimensionCable'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbChauffage', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbInterrupteur', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbSortieLumieres', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbPriseElectrique', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'nbVoletRoulant', '' . "\0" . 'App\\Entity\\Electricite' . "\0" . 'dimensionCable'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Electricite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbChauffage(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbChauffage', []);

        return parent::getNbChauffage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbChauffage(int $nbChauffage): \App\Entity\Electricite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbChauffage', [$nbChauffage]);

        return parent::setNbChauffage($nbChauffage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbInterrupteur(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbInterrupteur', []);

        return parent::getNbInterrupteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbInterrupteur(int $nbInterrupteur): \App\Entity\Electricite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbInterrupteur', [$nbInterrupteur]);

        return parent::setNbInterrupteur($nbInterrupteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbSortieLumieres(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbSortieLumieres', []);

        return parent::getNbSortieLumieres();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbSortieLumieres(int $nbSortieLumieres): \App\Entity\Electricite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbSortieLumieres', [$nbSortieLumieres]);

        return parent::setNbSortieLumieres($nbSortieLumieres);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPriseElectrique(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPriseElectrique', []);

        return parent::getNbPriseElectrique();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPriseElectrique(int $nbPriseElectrique): \App\Entity\Electricite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPriseElectrique', [$nbPriseElectrique]);

        return parent::setNbPriseElectrique($nbPriseElectrique);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbVoletRoulant(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbVoletRoulant', []);

        return parent::getNbVoletRoulant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbVoletRoulant(int $nbVoletRoulant): \App\Entity\Electricite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbVoletRoulant', [$nbVoletRoulant]);

        return parent::setNbVoletRoulant($nbVoletRoulant);
    }

    /**
     * {@inheritDoc}
     */
    public function getDimensionCable(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDimensionCable', []);

        return parent::getDimensionCable();
    }

    /**
     * {@inheritDoc}
     */
    public function setDimensionCable(float $dimensionCable): \App\Entity\Electricite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDimensionCable', [$dimensionCable]);

        return parent::setDimensionCable($dimensionCable);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\Electricite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

}
