<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Soubassement extends \App\Entity\Soubassement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'typeSoubassement', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'materielUtilise', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'tractopelle', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'camion_benne', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'betonniere'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'typeSoubassement', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'materielUtilise', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'tractopelle', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'camion_benne', '' . "\0" . 'App\\Entity\\Soubassement' . "\0" . 'betonniere'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Soubassement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeSoubassement(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeSoubassement', []);

        return parent::getTypeSoubassement();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeSoubassement(string $typeSoubassement): \App\Entity\Soubassement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeSoubassement', [$typeSoubassement]);

        return parent::setTypeSoubassement($typeSoubassement);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaterielUtilise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaterielUtilise', []);

        return parent::getMaterielUtilise();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaterielUtilise(?string $materielUtilise): \App\Entity\Soubassement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaterielUtilise', [$materielUtilise]);

        return parent::setMaterielUtilise($materielUtilise);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(float $prix): \App\Entity\Soubassement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getTractopelle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTractopelle', []);

        return parent::getTractopelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTractopelle(?string $tractopelle): \App\Entity\Soubassement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTractopelle', [$tractopelle]);

        return parent::setTractopelle($tractopelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCamionBenne(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCamionBenne', []);

        return parent::getCamionBenne();
    }

    /**
     * {@inheritDoc}
     */
    public function setCamionBenne(?string $camion_benne): \App\Entity\Soubassement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCamionBenne', [$camion_benne]);

        return parent::setCamionBenne($camion_benne);
    }

    /**
     * {@inheritDoc}
     */
    public function getBetonniere(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBetonniere', []);

        return parent::getBetonniere();
    }

    /**
     * {@inheritDoc}
     */
    public function setBetonniere(?string $betonniere): \App\Entity\Soubassement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBetonniere', [$betonniere]);

        return parent::setBetonniere($betonniere);
    }

}
